### PR TITLE
[HW-8] Update `run-linters.sh` script

### PR DESCRIPTION
**Pull request by AlexLevshenkov**
**The code has already been reviewed by the team:**
- https://github.com/AlexLevshenkov/ios-engineering-school-hws/pull/72

## List of changes

- `-f` option has been added to the `run-linters.sh` script;
- the instructions on how to run the `run-linters.sh` script have been updated in `CONTRIBUTING.md` file;

### CODE REVIEW

**Comment by Shadowman405** [comment]
In PR description you mentioned `README`

> the instructions on how to run the `run-linters.sh` script have been updated in `README.md` file;

Bit in this PR you changed only script file, is that ok ?? Or you should update something in `READMEmd` file ??

**Review by Nikitapls — APPROVED** [review]
LGTM.
Please take a look on [question](https://github.com/AlexLevshenkov/LifoContainers/pull/36#issuecomment-2198053115) by @ Shadowman405

**Comment by AlexLevshenkov** [comment]
> In PR description you mentioned `README`
> 
> > the instructions on how to run the `run-linters.sh` script have been updated in `README.md` file;
> 
> Bit in this PR you changed only script file, is that ok ?? Or you should update something in `READMEmd` file ??

I have changed the description and committed the missing part of the pull request

**Review by Shadowman405 — APPROVED** [review]

**Comment by AlexLevshenkov** [comment]
The pull request had been reviewed and then approved. All conversations were resolved. Merged

**Pull request merged**
