### PR TITLE
Update linters configs

### PR DESCRIPTION
**Pull request by AlexLevshenkov**
## List of changes

- the `.swiftformat` file has been updated;
- the `.swiftlint.yml` file has been updated;

### CODE REVIEW

**Comment by Nikitapls** [comment]
Please add the issue to this PR to describe the reason for this change.
@AlexLevshenkov

**Comment by AlexLevshenkov** [comment]
> Please add the issue to this PR to describe the reason for this change. @AlexLevshenkov

@Nikitapls added

**Review by Nikitapls — APPROVED** [review]
LGTM

**Review by Shadowman405 — APPROVED** [review]

**Comment by AlexLevshenkov** [comment]
The pull request had been reviewed and then approved. All conversations were resolved. Merged

**Pull request merged**
